image: maven:3.8.5-openjdk-17-slim

cache:
  paths:
    - .m2/

stages:
  - test
  - dependency_scan
  - build
  - deploy

# Test Stage
test:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mvn test -Dspring.profiles.active=test clean

# Dependency Scan Stage
dependency_scan:
  stage: dependency_scan
  image: owasp/dependency-check:latest
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh --scan /workspace/target --format ALL --project "Your_Project_Name" --out /workspace/dependency-check-report
  artifacts:
    paths:
      - dependency-check-report/

# Build Stage
build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar

# Deploy Stage
deploy:
  stage: deploy
  needs: ["build"]
  image: docker:latest
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  tags:
    - dind
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t reg.sysdevservices.tech/SERVICENAME:latest .
    - docker tag reg.sysdevservices.tech/SERVICENAME:latest reg.sysdevservices.tech/SERVICENAME:latest
    - docker push reg.sysdevservices.tech/SERVICENAME:latest
